//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace SFGWrapper.SFG.SubOrderInsertSvc {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="process_wsdl_classBinding", Namespace="urn:SubOrderInsert")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(optinresulttype))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(emailresulttype))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(errortype))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(optinlisttype))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(emaillisttype))]
    public partial class SubOrderInsertService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback process_wsdlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SubOrderInsertService() {
            this.Url = global::SFGWrapper.Properties.Settings.Default.SFGWrapper_com_strategicfulfillment_webservices_SubOrderInsertService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event process_wsdlCompletedEventHandler process_wsdlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:process_wsdl_classAction", RequestNamespace="urn:SubOrderInsert", ResponseNamespace="urn:SubOrderInsert")]
        [return: System.Xml.Serialization.SoapElementAttribute("process_wsdlReturn")]
        public returntype process_wsdl(argtype args) {
            object[] results = this.Invoke("process_wsdl", new object[] {
                        args});
            return ((returntype)(results[0]));
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args) {
            this.process_wsdlAsync(args, null);
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args, object userState) {
            if ((this.process_wsdlOperationCompleted == null)) {
                this.process_wsdlOperationCompleted = new System.Threading.SendOrPostCallback(this.Onprocess_wsdlOperationCompleted);
            }
            this.InvokeAsync("process_wsdl", new object[] {
                        args}, this.process_wsdlOperationCompleted, userState);
        }
        
        private void Onprocess_wsdlOperationCompleted(object arg) {
            if ((this.process_wsdlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.process_wsdlCompleted(this, new process_wsdlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class argtype {
        
        private string orgField;
        
        private string program_type_idField;
        
        private string program_idField;
        
        private string test_modeField;
        
        private string as_partnerField;
        
        private string db_nameField;
        
        private string app_versionField;
        
        private string is_network_monitorField;
        
        private string as_emailField;
        
        private string refresh_customerField;
        
        private string key_codeField;
        
        private int termField;
        
        private int copiesField;
        
        private bool copiesFieldSpecified;
        
        private int start_issueField;
        
        private bool start_issueFieldSpecified;
        
        private string premium1Field;
        
        private string premium2Field;
        
        private string premium3Field;
        
        private string payment_typeField;
        
        private string cc_route_noField;
        
        private string currencyField;
        
        private string postageField;
        
        private string taxField;
        
        private string priceField;
        
        private string amount_paidField;
        
        private string auto_renewField;
        
        private string survey_trans_idField;
        
        private string customer_numberField;
        
        private string gift_flagField;
        
        private string gift_numberField;
        
        private string g_titleField;
        
        private string g_firstField;
        
        private string g_miField;
        
        private string g_lastField;
        
        private string g_suffixField;
        
        private string g_professional_titleField;
        
        private string g_business_nameField;
        
        private string g_add1Field;
        
        private string g_add2Field;
        
        private string g_add3Field;
        
        private string g_cityField;
        
        private string g_stField;
        
        private string g_zipField;
        
        private string g_countryField;
        
        private string g_phoneField;
        
        private string g_emailField;
        
        private string g_optinField;
        
        private emaillisttype[] g_email_listField;
        
        private optinlisttype[] g_optin_listField;
        
        private string c_titleField;
        
        private string c_firstField;
        
        private string c_miField;
        
        private string c_lastField;
        
        private string c_suffixField;
        
        private string c_professional_titleField;
        
        private string c_business_nameField;
        
        private string c_add1Field;
        
        private string c_add2Field;
        
        private string c_add3Field;
        
        private string c_cityField;
        
        private string c_stField;
        
        private string c_zipField;
        
        private string c_countryField;
        
        private string c_phoneField;
        
        private string c_faxField;
        
        private string c_emailField;
        
        private string c_altcityField;
        
        private string c_optinField;
        
        private emaillisttype[] c_email_listField;
        
        private optinlisttype[] c_optin_listField;
        
        /// <remarks/>
        public string org {
            get {
                return this.orgField;
            }
            set {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        public string program_type_id {
            get {
                return this.program_type_idField;
            }
            set {
                this.program_type_idField = value;
            }
        }
        
        /// <remarks/>
        public string program_id {
            get {
                return this.program_idField;
            }
            set {
                this.program_idField = value;
            }
        }
        
        /// <remarks/>
        public string test_mode {
            get {
                return this.test_modeField;
            }
            set {
                this.test_modeField = value;
            }
        }
        
        /// <remarks/>
        public string as_partner {
            get {
                return this.as_partnerField;
            }
            set {
                this.as_partnerField = value;
            }
        }
        
        /// <remarks/>
        public string db_name {
            get {
                return this.db_nameField;
            }
            set {
                this.db_nameField = value;
            }
        }
        
        /// <remarks/>
        public string app_version {
            get {
                return this.app_versionField;
            }
            set {
                this.app_versionField = value;
            }
        }
        
        /// <remarks/>
        public string is_network_monitor {
            get {
                return this.is_network_monitorField;
            }
            set {
                this.is_network_monitorField = value;
            }
        }
        
        /// <remarks/>
        public string as_email {
            get {
                return this.as_emailField;
            }
            set {
                this.as_emailField = value;
            }
        }
        
        /// <remarks/>
        public string refresh_customer {
            get {
                return this.refresh_customerField;
            }
            set {
                this.refresh_customerField = value;
            }
        }
        
        /// <remarks/>
        public string key_code {
            get {
                return this.key_codeField;
            }
            set {
                this.key_codeField = value;
            }
        }
        
        /// <remarks/>
        public int term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public int copies {
            get {
                return this.copiesField;
            }
            set {
                this.copiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool copiesSpecified {
            get {
                return this.copiesFieldSpecified;
            }
            set {
                this.copiesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int start_issue {
            get {
                return this.start_issueField;
            }
            set {
                this.start_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool start_issueSpecified {
            get {
                return this.start_issueFieldSpecified;
            }
            set {
                this.start_issueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string premium1 {
            get {
                return this.premium1Field;
            }
            set {
                this.premium1Field = value;
            }
        }
        
        /// <remarks/>
        public string premium2 {
            get {
                return this.premium2Field;
            }
            set {
                this.premium2Field = value;
            }
        }
        
        /// <remarks/>
        public string premium3 {
            get {
                return this.premium3Field;
            }
            set {
                this.premium3Field = value;
            }
        }
        
        /// <remarks/>
        public string payment_type {
            get {
                return this.payment_typeField;
            }
            set {
                this.payment_typeField = value;
            }
        }
        
        /// <remarks/>
        public string cc_route_no {
            get {
                return this.cc_route_noField;
            }
            set {
                this.cc_route_noField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string postage {
            get {
                return this.postageField;
            }
            set {
                this.postageField = value;
            }
        }
        
        /// <remarks/>
        public string tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string amount_paid {
            get {
                return this.amount_paidField;
            }
            set {
                this.amount_paidField = value;
            }
        }
        
        /// <remarks/>
        public string auto_renew {
            get {
                return this.auto_renewField;
            }
            set {
                this.auto_renewField = value;
            }
        }
        
        /// <remarks/>
        public string survey_trans_id {
            get {
                return this.survey_trans_idField;
            }
            set {
                this.survey_trans_idField = value;
            }
        }
        
        /// <remarks/>
        public string customer_number {
            get {
                return this.customer_numberField;
            }
            set {
                this.customer_numberField = value;
            }
        }
        
        /// <remarks/>
        public string gift_flag {
            get {
                return this.gift_flagField;
            }
            set {
                this.gift_flagField = value;
            }
        }
        
        /// <remarks/>
        public string gift_number {
            get {
                return this.gift_numberField;
            }
            set {
                this.gift_numberField = value;
            }
        }
        
        /// <remarks/>
        public string g_title {
            get {
                return this.g_titleField;
            }
            set {
                this.g_titleField = value;
            }
        }
        
        /// <remarks/>
        public string g_first {
            get {
                return this.g_firstField;
            }
            set {
                this.g_firstField = value;
            }
        }
        
        /// <remarks/>
        public string g_mi {
            get {
                return this.g_miField;
            }
            set {
                this.g_miField = value;
            }
        }
        
        /// <remarks/>
        public string g_last {
            get {
                return this.g_lastField;
            }
            set {
                this.g_lastField = value;
            }
        }
        
        /// <remarks/>
        public string g_suffix {
            get {
                return this.g_suffixField;
            }
            set {
                this.g_suffixField = value;
            }
        }
        
        /// <remarks/>
        public string g_professional_title {
            get {
                return this.g_professional_titleField;
            }
            set {
                this.g_professional_titleField = value;
            }
        }
        
        /// <remarks/>
        public string g_business_name {
            get {
                return this.g_business_nameField;
            }
            set {
                this.g_business_nameField = value;
            }
        }
        
        /// <remarks/>
        public string g_add1 {
            get {
                return this.g_add1Field;
            }
            set {
                this.g_add1Field = value;
            }
        }
        
        /// <remarks/>
        public string g_add2 {
            get {
                return this.g_add2Field;
            }
            set {
                this.g_add2Field = value;
            }
        }
        
        /// <remarks/>
        public string g_add3 {
            get {
                return this.g_add3Field;
            }
            set {
                this.g_add3Field = value;
            }
        }
        
        /// <remarks/>
        public string g_city {
            get {
                return this.g_cityField;
            }
            set {
                this.g_cityField = value;
            }
        }
        
        /// <remarks/>
        public string g_st {
            get {
                return this.g_stField;
            }
            set {
                this.g_stField = value;
            }
        }
        
        /// <remarks/>
        public string g_zip {
            get {
                return this.g_zipField;
            }
            set {
                this.g_zipField = value;
            }
        }
        
        /// <remarks/>
        public string g_country {
            get {
                return this.g_countryField;
            }
            set {
                this.g_countryField = value;
            }
        }
        
        /// <remarks/>
        public string g_phone {
            get {
                return this.g_phoneField;
            }
            set {
                this.g_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string g_email {
            get {
                return this.g_emailField;
            }
            set {
                this.g_emailField = value;
            }
        }
        
        /// <remarks/>
        public string g_optin {
            get {
                return this.g_optinField;
            }
            set {
                this.g_optinField = value;
            }
        }
        
        /// <remarks/>
        public emaillisttype[] g_email_list {
            get {
                return this.g_email_listField;
            }
            set {
                this.g_email_listField = value;
            }
        }
        
        /// <remarks/>
        public optinlisttype[] g_optin_list {
            get {
                return this.g_optin_listField;
            }
            set {
                this.g_optin_listField = value;
            }
        }
        
        /// <remarks/>
        public string c_title {
            get {
                return this.c_titleField;
            }
            set {
                this.c_titleField = value;
            }
        }
        
        /// <remarks/>
        public string c_first {
            get {
                return this.c_firstField;
            }
            set {
                this.c_firstField = value;
            }
        }
        
        /// <remarks/>
        public string c_mi {
            get {
                return this.c_miField;
            }
            set {
                this.c_miField = value;
            }
        }
        
        /// <remarks/>
        public string c_last {
            get {
                return this.c_lastField;
            }
            set {
                this.c_lastField = value;
            }
        }
        
        /// <remarks/>
        public string c_suffix {
            get {
                return this.c_suffixField;
            }
            set {
                this.c_suffixField = value;
            }
        }
        
        /// <remarks/>
        public string c_professional_title {
            get {
                return this.c_professional_titleField;
            }
            set {
                this.c_professional_titleField = value;
            }
        }
        
        /// <remarks/>
        public string c_business_name {
            get {
                return this.c_business_nameField;
            }
            set {
                this.c_business_nameField = value;
            }
        }
        
        /// <remarks/>
        public string c_add1 {
            get {
                return this.c_add1Field;
            }
            set {
                this.c_add1Field = value;
            }
        }
        
        /// <remarks/>
        public string c_add2 {
            get {
                return this.c_add2Field;
            }
            set {
                this.c_add2Field = value;
            }
        }
        
        /// <remarks/>
        public string c_add3 {
            get {
                return this.c_add3Field;
            }
            set {
                this.c_add3Field = value;
            }
        }
        
        /// <remarks/>
        public string c_city {
            get {
                return this.c_cityField;
            }
            set {
                this.c_cityField = value;
            }
        }
        
        /// <remarks/>
        public string c_st {
            get {
                return this.c_stField;
            }
            set {
                this.c_stField = value;
            }
        }
        
        /// <remarks/>
        public string c_zip {
            get {
                return this.c_zipField;
            }
            set {
                this.c_zipField = value;
            }
        }
        
        /// <remarks/>
        public string c_country {
            get {
                return this.c_countryField;
            }
            set {
                this.c_countryField = value;
            }
        }
        
        /// <remarks/>
        public string c_phone {
            get {
                return this.c_phoneField;
            }
            set {
                this.c_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string c_fax {
            get {
                return this.c_faxField;
            }
            set {
                this.c_faxField = value;
            }
        }
        
        /// <remarks/>
        public string c_email {
            get {
                return this.c_emailField;
            }
            set {
                this.c_emailField = value;
            }
        }
        
        /// <remarks/>
        public string c_altcity {
            get {
                return this.c_altcityField;
            }
            set {
                this.c_altcityField = value;
            }
        }
        
        /// <remarks/>
        public string c_optin {
            get {
                return this.c_optinField;
            }
            set {
                this.c_optinField = value;
            }
        }
        
        /// <remarks/>
        public emaillisttype[] c_email_list {
            get {
                return this.c_email_listField;
            }
            set {
                this.c_email_listField = value;
            }
        }
        
        /// <remarks/>
        public optinlisttype[] c_optin_list {
            get {
                return this.c_optin_listField;
            }
            set {
                this.c_optin_listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class emaillisttype {
        
        private string email_idField;
        
        private string emailField;
        
        private string customer_numberField;
        
        private string email_typeField;
        
        private string email_activeField;
        
        /// <remarks/>
        public string email_id {
            get {
                return this.email_idField;
            }
            set {
                this.email_idField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string customer_number {
            get {
                return this.customer_numberField;
            }
            set {
                this.customer_numberField = value;
            }
        }
        
        /// <remarks/>
        public string email_type {
            get {
                return this.email_typeField;
            }
            set {
                this.email_typeField = value;
            }
        }
        
        /// <remarks/>
        public string email_active {
            get {
                return this.email_activeField;
            }
            set {
                this.email_activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class optinresulttype {
        
        private string email_idField;
        
        private string emailField;
        
        private string customer_numberField;
        
        private string eptextidField;
        
        private string eptypeField;
        
        private string product_lineField;
        
        private string optinField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string[] errorsField;
        
        private string sourceField;
        
        /// <remarks/>
        public string email_id {
            get {
                return this.email_idField;
            }
            set {
                this.email_idField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string customer_number {
            get {
                return this.customer_numberField;
            }
            set {
                this.customer_numberField = value;
            }
        }
        
        /// <remarks/>
        public string eptextid {
            get {
                return this.eptextidField;
            }
            set {
                this.eptextidField = value;
            }
        }
        
        /// <remarks/>
        public string eptype {
            get {
                return this.eptypeField;
            }
            set {
                this.eptypeField = value;
            }
        }
        
        /// <remarks/>
        public string product_line {
            get {
                return this.product_lineField;
            }
            set {
                this.product_lineField = value;
            }
        }
        
        /// <remarks/>
        public string optin {
            get {
                return this.optinField;
            }
            set {
                this.optinField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class emailresulttype {
        
        private string email_idField;
        
        private string emailField;
        
        private string customer_numberField;
        
        private string email_typeField;
        
        private string email_activeField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string[] errorsField;
        
        private string sourceField;
        
        private string update_allField;
        
        private string process_typeField;
        
        private string email_statusField;
        
        /// <remarks/>
        public string email_id {
            get {
                return this.email_idField;
            }
            set {
                this.email_idField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string customer_number {
            get {
                return this.customer_numberField;
            }
            set {
                this.customer_numberField = value;
            }
        }
        
        /// <remarks/>
        public string email_type {
            get {
                return this.email_typeField;
            }
            set {
                this.email_typeField = value;
            }
        }
        
        /// <remarks/>
        public string email_active {
            get {
                return this.email_activeField;
            }
            set {
                this.email_activeField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string update_all {
            get {
                return this.update_allField;
            }
            set {
                this.update_allField = value;
            }
        }
        
        /// <remarks/>
        public string process_type {
            get {
                return this.process_typeField;
            }
            set {
                this.process_typeField = value;
            }
        }
        
        /// <remarks/>
        public string email_status {
            get {
                return this.email_statusField;
            }
            set {
                this.email_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class responsetype {
        
        private string oRDER_ADDEDField;
        
        private string cUSTOMER_NUMBERField;
        
        private string cUSTOMER_UPDATEDField;
        
        private emailresulttype[] c_EMAIL_RESULTSField;
        
        private optinresulttype[] c_OPTIN_RESULTSField;
        
        private emailresulttype[] g_EMAIL_RESULTSField;
        
        private optinresulttype[] g_OPTIN_RESULTSField;
        
        private string tIME_ELAPSEDField;
        
        private string rOUNDTRIP_TIMEField;
        
        private string mEMORY_USEDField;
        
        private string pROTOCOLField;
        
        private string vERSIONField;
        
        private string sERVERField;
        
        private string[] iNFOField;
        
        /// <remarks/>
        public string ORDER_ADDED {
            get {
                return this.oRDER_ADDEDField;
            }
            set {
                this.oRDER_ADDEDField = value;
            }
        }
        
        /// <remarks/>
        public string CUSTOMER_NUMBER {
            get {
                return this.cUSTOMER_NUMBERField;
            }
            set {
                this.cUSTOMER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string CUSTOMER_UPDATED {
            get {
                return this.cUSTOMER_UPDATEDField;
            }
            set {
                this.cUSTOMER_UPDATEDField = value;
            }
        }
        
        /// <remarks/>
        public emailresulttype[] C_EMAIL_RESULTS {
            get {
                return this.c_EMAIL_RESULTSField;
            }
            set {
                this.c_EMAIL_RESULTSField = value;
            }
        }
        
        /// <remarks/>
        public optinresulttype[] C_OPTIN_RESULTS {
            get {
                return this.c_OPTIN_RESULTSField;
            }
            set {
                this.c_OPTIN_RESULTSField = value;
            }
        }
        
        /// <remarks/>
        public emailresulttype[] G_EMAIL_RESULTS {
            get {
                return this.g_EMAIL_RESULTSField;
            }
            set {
                this.g_EMAIL_RESULTSField = value;
            }
        }
        
        /// <remarks/>
        public optinresulttype[] G_OPTIN_RESULTS {
            get {
                return this.g_OPTIN_RESULTSField;
            }
            set {
                this.g_OPTIN_RESULTSField = value;
            }
        }
        
        /// <remarks/>
        public string TIME_ELAPSED {
            get {
                return this.tIME_ELAPSEDField;
            }
            set {
                this.tIME_ELAPSEDField = value;
            }
        }
        
        /// <remarks/>
        public string ROUNDTRIP_TIME {
            get {
                return this.rOUNDTRIP_TIMEField;
            }
            set {
                this.rOUNDTRIP_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY_USED {
            get {
                return this.mEMORY_USEDField;
            }
            set {
                this.mEMORY_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string PROTOCOL {
            get {
                return this.pROTOCOLField;
            }
            set {
                this.pROTOCOLField = value;
            }
        }
        
        /// <remarks/>
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
            }
        }
        
        /// <remarks/>
        public string SERVER {
            get {
                return this.sERVERField;
            }
            set {
                this.sERVERField = value;
            }
        }
        
        /// <remarks/>
        public string[] INFO {
            get {
                return this.iNFOField;
            }
            set {
                this.iNFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class errortype {
        
        private string[] errmsgField;
        
        private string errnoField;
        
        /// <remarks/>
        public string[] errmsg {
            get {
                return this.errmsgField;
            }
            set {
                this.errmsgField = value;
            }
        }
        
        /// <remarks/>
        public string errno {
            get {
                return this.errnoField;
            }
            set {
                this.errnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class returntype {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private errortype[] errorField;
        
        private responsetype responseField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public errortype[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public responsetype response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SubOrderInsert")]
    public partial class optinlisttype {
        
        private string email_idField;
        
        private string emailField;
        
        private string customer_numberField;
        
        private string eptextidField;
        
        private string eptypeField;
        
        private string product_lineField;
        
        private string optinField;
        
        /// <remarks/>
        public string email_id {
            get {
                return this.email_idField;
            }
            set {
                this.email_idField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string customer_number {
            get {
                return this.customer_numberField;
            }
            set {
                this.customer_numberField = value;
            }
        }
        
        /// <remarks/>
        public string eptextid {
            get {
                return this.eptextidField;
            }
            set {
                this.eptextidField = value;
            }
        }
        
        /// <remarks/>
        public string eptype {
            get {
                return this.eptypeField;
            }
            set {
                this.eptypeField = value;
            }
        }
        
        /// <remarks/>
        public string product_line {
            get {
                return this.product_lineField;
            }
            set {
                this.product_lineField = value;
            }
        }
        
        /// <remarks/>
        public string optin {
            get {
                return this.optinField;
            }
            set {
                this.optinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void process_wsdlCompletedEventHandler(object sender, process_wsdlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class process_wsdlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal process_wsdlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returntype Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returntype)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591