//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessLogicStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessLogicStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogic.BusinessLogicStrings", typeof(BusinessLogicStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This referral offer is available only to new members..
        /// </summary>
        internal static string cannotReferSelfError {
            get {
                return ResourceManager.GetString("cannotReferSelfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create username/pwd after processing referral {0} user {1}, pwd {2}.
        /// </summary>
        internal static string createUsernameError {
            get {
                return ResourceManager.GetString("createUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person you referred is already a current Andrew Harper member.  Please enter information for others you would like to refer for a complimentary membership..
        /// </summary>
        internal static string existingMemberError {
            get {
                return ResourceManager.GetString("existingMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another member has already referred your friend to Andrew Harper.  Please enter information for others you would like to refer for a complimentary membership..
        /// </summary>
        internal static string existingReferralError {
            get {
                return ResourceManager.GetString("existingReferralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process referral - referral {0} has expired.
        /// </summary>
        internal static string expiredReferralError {
            get {
                return ResourceManager.GetString("expiredReferralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral email in use.
        /// </summary>
        internal static string freindEmailInUseAHError {
            get {
                return ResourceManager.GetString("freindEmailInUseAHError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral email in use.
        /// </summary>
        internal static string freindEmailInUseSFGError {
            get {
                return ResourceManager.GetString("freindEmailInUseSFGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect memberid.
        /// </summary>
        internal static string invalidMemberIdError {
            get {
                return ResourceManager.GetString("invalidMemberIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process referral - referral id {0} is invalid.
        /// </summary>
        internal static string invalidReferralIdError {
            get {
                return ResourceManager.GetString("invalidReferralIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid memberid. Member does not exist..
        /// </summary>
        internal static string memberDoesNotExistError {
            get {
                return ResourceManager.GetString("memberDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend email address is null or empty.
        /// </summary>
        internal static string missingFriendEmailError {
            get {
                return ResourceManager.GetString("missingFriendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend name is null or empty.
        /// </summary>
        internal static string missingFriendNameError {
            get {
                return ResourceManager.GetString("missingFriendNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keycode is null or empty.
        /// </summary>
        internal static string missingKeycodeError {
            get {
                return ResourceManager.GetString("missingKeycodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member email is null or empty.
        /// </summary>
        internal static string missingMemberEmailError {
            get {
                return ResourceManager.GetString("missingMemberEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member name is null or empty.
        /// </summary>
        internal static string missingMemberNameError {
            get {
                return ResourceManager.GetString("missingMemberNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pubcode is null or empty.
        /// </summary>
        internal static string missingPubcodeError {
            get {
                return ResourceManager.GetString("missingPubcodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process referral - referral {0} has already been redeemed.
        /// </summary>
        internal static string RedeemedReferralError {
            get {
                return ResourceManager.GetString("RedeemedReferralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get member after processing referral {0} email {1}.
        /// </summary>
        internal static string RetrieveMemeberError {
            get {
                return ResourceManager.GetString("RetrieveMemeberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process referral - {0}.
        /// </summary>
        internal static string UnknownReferralError {
            get {
                return ResourceManager.GetString("UnknownReferralError", resourceCulture);
            }
        }
    }
}
