//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace SFGWrapper.SFG.CustomerUpdateSvc {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="process_wsdl_classBinding", Namespace="urn:CustomerUpdate")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(errortype))]
    public partial class CustomerUpdateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback process_wsdlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerUpdateService() {
            this.Url = global::SFGWrapper.Properties.Settings.Default.SFGWrapper_SFG_CustomerUpdateSvc_CustomerUpdateService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event process_wsdlCompletedEventHandler process_wsdlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:process_wsdl_classAction", RequestNamespace="urn:CustomerUpdate", ResponseNamespace="urn:CustomerUpdate")]
        [return: System.Xml.Serialization.SoapElementAttribute("process_wsdlReturn")]
        public returntype process_wsdl(argtype args) {
            object[] results = this.Invoke("process_wsdl", new object[] {
                        args});
            return ((returntype)(results[0]));
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args) {
            this.process_wsdlAsync(args, null);
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args, object userState) {
            if ((this.process_wsdlOperationCompleted == null)) {
                this.process_wsdlOperationCompleted = new System.Threading.SendOrPostCallback(this.Onprocess_wsdlOperationCompleted);
            }
            this.InvokeAsync("process_wsdl", new object[] {
                        args}, this.process_wsdlOperationCompleted, userState);
        }
        
        private void Onprocess_wsdlOperationCompleted(object arg) {
            if ((this.process_wsdlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.process_wsdlCompleted(this, new process_wsdlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:CustomerUpdate")]
    public partial class argtype {
        
        private string orgField;
        
        private string program_type_idField;
        
        private string program_idField;
        
        private string test_modeField;
        
        private string as_partnerField;
        
        private string db_nameField;
        
        private string app_versionField;
        
        private string is_network_monitorField;
        
        private string as_emailField;
        
        private string firstField;
        
        private string miField;
        
        private string lastField;
        
        private string business_nameField;
        
        private string professional_titleField;
        
        private string add1Field;
        
        private string add2Field;
        
        private string add3Field;
        
        private string cityField;
        
        private string stField;
        
        private string zipField;
        
        private string countryField;
        
        private string phoneField;
        
        private string faxField;
        
        private string titleField;
        
        private string suffixField;
        
        private string emailField;
        
        private string altcityField;
        
        private string optinField;
        
        private string customer_numberField;
        
        /// <remarks/>
        public string org {
            get {
                return this.orgField;
            }
            set {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        public string program_type_id {
            get {
                return this.program_type_idField;
            }
            set {
                this.program_type_idField = value;
            }
        }
        
        /// <remarks/>
        public string program_id {
            get {
                return this.program_idField;
            }
            set {
                this.program_idField = value;
            }
        }
        
        /// <remarks/>
        public string test_mode {
            get {
                return this.test_modeField;
            }
            set {
                this.test_modeField = value;
            }
        }
        
        /// <remarks/>
        public string as_partner {
            get {
                return this.as_partnerField;
            }
            set {
                this.as_partnerField = value;
            }
        }
        
        /// <remarks/>
        public string db_name {
            get {
                return this.db_nameField;
            }
            set {
                this.db_nameField = value;
            }
        }
        
        /// <remarks/>
        public string app_version {
            get {
                return this.app_versionField;
            }
            set {
                this.app_versionField = value;
            }
        }
        
        /// <remarks/>
        public string is_network_monitor {
            get {
                return this.is_network_monitorField;
            }
            set {
                this.is_network_monitorField = value;
            }
        }
        
        /// <remarks/>
        public string as_email {
            get {
                return this.as_emailField;
            }
            set {
                this.as_emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string first {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mi {
            get {
                return this.miField;
            }
            set {
                this.miField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string business_name {
            get {
                return this.business_nameField;
            }
            set {
                this.business_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string professional_title {
            get {
                return this.professional_titleField;
            }
            set {
                this.professional_titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string add1 {
            get {
                return this.add1Field;
            }
            set {
                this.add1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string add2 {
            get {
                return this.add2Field;
            }
            set {
                this.add2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string add3 {
            get {
                return this.add3Field;
            }
            set {
                this.add3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string st {
            get {
                return this.stField;
            }
            set {
                this.stField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string altcity {
            get {
                return this.altcityField;
            }
            set {
                this.altcityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string optin {
            get {
                return this.optinField;
            }
            set {
                this.optinField = value;
            }
        }
        
        /// <remarks/>
        public string customer_number {
            get {
                return this.customer_numberField;
            }
            set {
                this.customer_numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:CustomerUpdate")]
    public partial class responsetype {
        
        private string cUSTOMER_UPDATEDField;
        
        private string tIME_ELAPSEDField;
        
        private string rOUNDTRIP_TIMEField;
        
        private string mEMORY_USEDField;
        
        private string pROTOCOLField;
        
        private string vERSIONField;
        
        private string sERVERField;
        
        private string[] iNFOField;
        
        /// <remarks/>
        public string CUSTOMER_UPDATED {
            get {
                return this.cUSTOMER_UPDATEDField;
            }
            set {
                this.cUSTOMER_UPDATEDField = value;
            }
        }
        
        /// <remarks/>
        public string TIME_ELAPSED {
            get {
                return this.tIME_ELAPSEDField;
            }
            set {
                this.tIME_ELAPSEDField = value;
            }
        }
        
        /// <remarks/>
        public string ROUNDTRIP_TIME {
            get {
                return this.rOUNDTRIP_TIMEField;
            }
            set {
                this.rOUNDTRIP_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY_USED {
            get {
                return this.mEMORY_USEDField;
            }
            set {
                this.mEMORY_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string PROTOCOL {
            get {
                return this.pROTOCOLField;
            }
            set {
                this.pROTOCOLField = value;
            }
        }
        
        /// <remarks/>
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
            }
        }
        
        /// <remarks/>
        public string SERVER {
            get {
                return this.sERVERField;
            }
            set {
                this.sERVERField = value;
            }
        }
        
        /// <remarks/>
        public string[] INFO {
            get {
                return this.iNFOField;
            }
            set {
                this.iNFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:CustomerUpdate")]
    public partial class errortype {
        
        private string[] errmsgField;
        
        private string errnoField;
        
        /// <remarks/>
        public string[] errmsg {
            get {
                return this.errmsgField;
            }
            set {
                this.errmsgField = value;
            }
        }
        
        /// <remarks/>
        public string errno {
            get {
                return this.errnoField;
            }
            set {
                this.errnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:CustomerUpdate")]
    public partial class returntype {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private errortype[] errorField;
        
        private responsetype responseField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public errortype[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public responsetype response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void process_wsdlCompletedEventHandler(object sender, process_wsdlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class process_wsdlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal process_wsdlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returntype Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returntype)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591