//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace SFGWrapper.SFG.GateKeeperSvc {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="process_wsdl_classBinding", Namespace="urn:GateKeeper")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(suboffertype))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(orderhistorytype))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(errortype))]
    public partial class GateKeeperService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback process_wsdlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GateKeeperService() {
            this.Url = global::SFGWrapper.Properties.Settings.Default.SFGWrapper_SFG_GateKeeperSvc_GateKeeperService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event process_wsdlCompletedEventHandler process_wsdlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:process_wsdl_classAction", RequestNamespace="urn:GateKeeper", ResponseNamespace="urn:GateKeeper")]
        [return: System.Xml.Serialization.SoapElementAttribute("process_wsdlReturn")]
        public returntype process_wsdl(argtype args) {
            object[] results = this.Invoke("process_wsdl", new object[] {
                        args});
            return ((returntype)(results[0]));
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args) {
            this.process_wsdlAsync(args, null);
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args, object userState) {
            if ((this.process_wsdlOperationCompleted == null)) {
                this.process_wsdlOperationCompleted = new System.Threading.SendOrPostCallback(this.Onprocess_wsdlOperationCompleted);
            }
            this.InvokeAsync("process_wsdl", new object[] {
                        args}, this.process_wsdlOperationCompleted, userState);
        }
        
        private void Onprocess_wsdlOperationCompleted(object arg) {
            if ((this.process_wsdlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.process_wsdlCompleted(this, new process_wsdlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class argtype {
        
        private string orgField;
        
        private string program_type_idField;
        
        private string program_idField;
        
        private string test_modeField;
        
        private string as_partnerField;
        
        private string db_nameField;
        
        private string app_versionField;
        
        private string is_network_monitorField;
        
        private string as_emailField;
        
        private string useridField;
        
        private string pwField;
        
        private string customer_numberField;
        
        private string zipField;
        
        private string firstField;
        
        private string lastField;
        
        private string addressField;
        
        private string countryField;
        
        private string hashed_pwField;
        
        private string check_pwField;
        
        private string load_customerField;
        
        private string load_historyField;
        
        private string validate_subscriptionField;
        
        private string load_renewal_offersField;
        
        private string load_optin_listField;
        
        private string offers_key_codeField;
        
        private int days_historyField;
        
        private string login_asField;
        
        private string search_by_custnoField;
        
        /// <remarks/>
        public string org {
            get {
                return this.orgField;
            }
            set {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        public string program_type_id {
            get {
                return this.program_type_idField;
            }
            set {
                this.program_type_idField = value;
            }
        }
        
        /// <remarks/>
        public string program_id {
            get {
                return this.program_idField;
            }
            set {
                this.program_idField = value;
            }
        }
        
        /// <remarks/>
        public string test_mode {
            get {
                return this.test_modeField;
            }
            set {
                this.test_modeField = value;
            }
        }
        
        /// <remarks/>
        public string as_partner {
            get {
                return this.as_partnerField;
            }
            set {
                this.as_partnerField = value;
            }
        }
        
        /// <remarks/>
        public string db_name {
            get {
                return this.db_nameField;
            }
            set {
                this.db_nameField = value;
            }
        }
        
        /// <remarks/>
        public string app_version {
            get {
                return this.app_versionField;
            }
            set {
                this.app_versionField = value;
            }
        }
        
        /// <remarks/>
        public string is_network_monitor {
            get {
                return this.is_network_monitorField;
            }
            set {
                this.is_network_monitorField = value;
            }
        }
        
        /// <remarks/>
        public string as_email {
            get {
                return this.as_emailField;
            }
            set {
                this.as_emailField = value;
            }
        }
        
        /// <remarks/>
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        public string pw {
            get {
                return this.pwField;
            }
            set {
                this.pwField = value;
            }
        }
        
        /// <remarks/>
        public string customer_number {
            get {
                return this.customer_numberField;
            }
            set {
                this.customer_numberField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string first {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        public string last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string hashed_pw {
            get {
                return this.hashed_pwField;
            }
            set {
                this.hashed_pwField = value;
            }
        }
        
        /// <remarks/>
        public string check_pw {
            get {
                return this.check_pwField;
            }
            set {
                this.check_pwField = value;
            }
        }
        
        /// <remarks/>
        public string load_customer {
            get {
                return this.load_customerField;
            }
            set {
                this.load_customerField = value;
            }
        }
        
        /// <remarks/>
        public string load_history {
            get {
                return this.load_historyField;
            }
            set {
                this.load_historyField = value;
            }
        }
        
        /// <remarks/>
        public string validate_subscription {
            get {
                return this.validate_subscriptionField;
            }
            set {
                this.validate_subscriptionField = value;
            }
        }
        
        /// <remarks/>
        public string load_renewal_offers {
            get {
                return this.load_renewal_offersField;
            }
            set {
                this.load_renewal_offersField = value;
            }
        }
        
        /// <remarks/>
        public string load_optin_list {
            get {
                return this.load_optin_listField;
            }
            set {
                this.load_optin_listField = value;
            }
        }
        
        /// <remarks/>
        public string offers_key_code {
            get {
                return this.offers_key_codeField;
            }
            set {
                this.offers_key_codeField = value;
            }
        }
        
        /// <remarks/>
        public int days_history {
            get {
                return this.days_historyField;
            }
            set {
                this.days_historyField = value;
            }
        }
        
        /// <remarks/>
        public string login_as {
            get {
                return this.login_asField;
            }
            set {
                this.login_asField = value;
            }
        }
        
        /// <remarks/>
        public string search_by_custno {
            get {
                return this.search_by_custnoField;
            }
            set {
                this.search_by_custnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class suboffertype {
        
        private string kEY_CODEField;
        
        private string pUBLICATION_CODEField;
        
        private string aGENCY_CODEField;
        
        private string cOUNTRY_CODEField;
        
        private string sUB_RENEWAL_FLAGField;
        
        private string sUBSCRIPTION_TERMField;
        
        private string cASH_OR_CREDIT_OFFERField;
        
        private string gROSS_VALUEField;
        
        private string sTART_DATEField;
        
        private string sTART_ISSUEField;
        
        private string nUMBER_FREE_ISSUESField;
        
        private string sTART_BILLING_ISSUEField;
        
        private string nUMBER_GRACE_ISSUESField;
        
        private string nUMBER_OF_INSTALLMENTSField;
        
        private string pOSTAGEField;
        
        /// <remarks/>
        public string KEY_CODE {
            get {
                return this.kEY_CODEField;
            }
            set {
                this.kEY_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PUBLICATION_CODE {
            get {
                return this.pUBLICATION_CODEField;
            }
            set {
                this.pUBLICATION_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string AGENCY_CODE {
            get {
                return this.aGENCY_CODEField;
            }
            set {
                this.aGENCY_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string COUNTRY_CODE {
            get {
                return this.cOUNTRY_CODEField;
            }
            set {
                this.cOUNTRY_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string SUB_RENEWAL_FLAG {
            get {
                return this.sUB_RENEWAL_FLAGField;
            }
            set {
                this.sUB_RENEWAL_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string SUBSCRIPTION_TERM {
            get {
                return this.sUBSCRIPTION_TERMField;
            }
            set {
                this.sUBSCRIPTION_TERMField = value;
            }
        }
        
        /// <remarks/>
        public string CASH_OR_CREDIT_OFFER {
            get {
                return this.cASH_OR_CREDIT_OFFERField;
            }
            set {
                this.cASH_OR_CREDIT_OFFERField = value;
            }
        }
        
        /// <remarks/>
        public string GROSS_VALUE {
            get {
                return this.gROSS_VALUEField;
            }
            set {
                this.gROSS_VALUEField = value;
            }
        }
        
        /// <remarks/>
        public string START_DATE {
            get {
                return this.sTART_DATEField;
            }
            set {
                this.sTART_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string START_ISSUE {
            get {
                return this.sTART_ISSUEField;
            }
            set {
                this.sTART_ISSUEField = value;
            }
        }
        
        /// <remarks/>
        public string NUMBER_FREE_ISSUES {
            get {
                return this.nUMBER_FREE_ISSUESField;
            }
            set {
                this.nUMBER_FREE_ISSUESField = value;
            }
        }
        
        /// <remarks/>
        public string START_BILLING_ISSUE {
            get {
                return this.sTART_BILLING_ISSUEField;
            }
            set {
                this.sTART_BILLING_ISSUEField = value;
            }
        }
        
        /// <remarks/>
        public string NUMBER_GRACE_ISSUES {
            get {
                return this.nUMBER_GRACE_ISSUESField;
            }
            set {
                this.nUMBER_GRACE_ISSUESField = value;
            }
        }
        
        /// <remarks/>
        public string NUMBER_OF_INSTALLMENTS {
            get {
                return this.nUMBER_OF_INSTALLMENTSField;
            }
            set {
                this.nUMBER_OF_INSTALLMENTSField = value;
            }
        }
        
        /// <remarks/>
        public string POSTAGE {
            get {
                return this.pOSTAGEField;
            }
            set {
                this.pOSTAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class orderhistorytype {
        
        private string cATEGORYField;
        
        private string pROD_CODEField;
        
        private string dESCRIPTIONField;
        
        private string qTYField;
        
        private string dATEField;
        
        private string eXPIRE_DATEField;
        
        private string iSS_REMField;
        
        private string rENEWAL_KEYCODEField;
        
        private string ePUBField;
        
        private string h_CUSTField;
        
        private string g_CUSTField;
        
        private string sTATUS_FLAGField;
        
        private string iS_GIFTField;
        
        private string iS_DONORField;
        
        /// <remarks/>
        public string CATEGORY {
            get {
                return this.cATEGORYField;
            }
            set {
                this.cATEGORYField = value;
            }
        }
        
        /// <remarks/>
        public string PROD_CODE {
            get {
                return this.pROD_CODEField;
            }
            set {
                this.pROD_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public string QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        public string DATE {
            get {
                return this.dATEField;
            }
            set {
                this.dATEField = value;
            }
        }
        
        /// <remarks/>
        public string EXPIRE_DATE {
            get {
                return this.eXPIRE_DATEField;
            }
            set {
                this.eXPIRE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string ISS_REM {
            get {
                return this.iSS_REMField;
            }
            set {
                this.iSS_REMField = value;
            }
        }
        
        /// <remarks/>
        public string RENEWAL_KEYCODE {
            get {
                return this.rENEWAL_KEYCODEField;
            }
            set {
                this.rENEWAL_KEYCODEField = value;
            }
        }
        
        /// <remarks/>
        public string EPUB {
            get {
                return this.ePUBField;
            }
            set {
                this.ePUBField = value;
            }
        }
        
        /// <remarks/>
        public string H_CUST {
            get {
                return this.h_CUSTField;
            }
            set {
                this.h_CUSTField = value;
            }
        }
        
        /// <remarks/>
        public string G_CUST {
            get {
                return this.g_CUSTField;
            }
            set {
                this.g_CUSTField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS_FLAG {
            get {
                return this.sTATUS_FLAGField;
            }
            set {
                this.sTATUS_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string IS_GIFT {
            get {
                return this.iS_GIFTField;
            }
            set {
                this.iS_GIFTField = value;
            }
        }
        
        /// <remarks/>
        public string IS_DONOR {
            get {
                return this.iS_DONORField;
            }
            set {
                this.iS_DONORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class shiptotype {
        
        private string sBUSINESSField;
        
        private string sADDR1Field;
        
        private string sADDR2Field;
        
        private string sADDR3Field;
        
        private string sCITYField;
        
        private string sSTField;
        
        private string sZIPField;
        
        private string sCOUNTRYField;
        
        private string sPHONEField;
        
        private string sTITLEField;
        
        private string sSUFFIXField;
        
        /// <remarks/>
        public string SBUSINESS {
            get {
                return this.sBUSINESSField;
            }
            set {
                this.sBUSINESSField = value;
            }
        }
        
        /// <remarks/>
        public string SADDR1 {
            get {
                return this.sADDR1Field;
            }
            set {
                this.sADDR1Field = value;
            }
        }
        
        /// <remarks/>
        public string SADDR2 {
            get {
                return this.sADDR2Field;
            }
            set {
                this.sADDR2Field = value;
            }
        }
        
        /// <remarks/>
        public string SADDR3 {
            get {
                return this.sADDR3Field;
            }
            set {
                this.sADDR3Field = value;
            }
        }
        
        /// <remarks/>
        public string SCITY {
            get {
                return this.sCITYField;
            }
            set {
                this.sCITYField = value;
            }
        }
        
        /// <remarks/>
        public string SST {
            get {
                return this.sSTField;
            }
            set {
                this.sSTField = value;
            }
        }
        
        /// <remarks/>
        public string SZIP {
            get {
                return this.sZIPField;
            }
            set {
                this.sZIPField = value;
            }
        }
        
        /// <remarks/>
        public string SCOUNTRY {
            get {
                return this.sCOUNTRYField;
            }
            set {
                this.sCOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        public string SPHONE {
            get {
                return this.sPHONEField;
            }
            set {
                this.sPHONEField = value;
            }
        }
        
        /// <remarks/>
        public string STITLE {
            get {
                return this.sTITLEField;
            }
            set {
                this.sTITLEField = value;
            }
        }
        
        /// <remarks/>
        public string SSUFFIX {
            get {
                return this.sSUFFIXField;
            }
            set {
                this.sSUFFIXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class customerinfotype {
        
        private string cUSTOMER_NUMBERField;
        
        private string fIRSTField;
        
        private string miField;
        
        private string lASTField;
        
        private string pROFESSIONAL_TITLEField;
        
        private string bUSINESS_NAMEField;
        
        private string aDD1Field;
        
        private string aDD2Field;
        
        private string aDD3Field;
        
        private string cITYField;
        
        private string stField;
        
        private string sTATE_NAMEField;
        
        private string zIPField;
        
        private string cOUNTRYField;
        
        private string pHONEField;
        
        private string tITLEField;
        
        private string sUFFIXField;
        
        private string eMAILField;
        
        private string ePREFField;
        
        private string oPTINField;
        
        private string aLTCITYField;
        
        private string sTATUSField;
        
        private string sTATUS_DESCField;
        
        /// <remarks/>
        public string CUSTOMER_NUMBER {
            get {
                return this.cUSTOMER_NUMBERField;
            }
            set {
                this.cUSTOMER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string FIRST {
            get {
                return this.fIRSTField;
            }
            set {
                this.fIRSTField = value;
            }
        }
        
        /// <remarks/>
        public string MI {
            get {
                return this.miField;
            }
            set {
                this.miField = value;
            }
        }
        
        /// <remarks/>
        public string LAST {
            get {
                return this.lASTField;
            }
            set {
                this.lASTField = value;
            }
        }
        
        /// <remarks/>
        public string PROFESSIONAL_TITLE {
            get {
                return this.pROFESSIONAL_TITLEField;
            }
            set {
                this.pROFESSIONAL_TITLEField = value;
            }
        }
        
        /// <remarks/>
        public string BUSINESS_NAME {
            get {
                return this.bUSINESS_NAMEField;
            }
            set {
                this.bUSINESS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ADD1 {
            get {
                return this.aDD1Field;
            }
            set {
                this.aDD1Field = value;
            }
        }
        
        /// <remarks/>
        public string ADD2 {
            get {
                return this.aDD2Field;
            }
            set {
                this.aDD2Field = value;
            }
        }
        
        /// <remarks/>
        public string ADD3 {
            get {
                return this.aDD3Field;
            }
            set {
                this.aDD3Field = value;
            }
        }
        
        /// <remarks/>
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        public string ST {
            get {
                return this.stField;
            }
            set {
                this.stField = value;
            }
        }
        
        /// <remarks/>
        public string STATE_NAME {
            get {
                return this.sTATE_NAMEField;
            }
            set {
                this.sTATE_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
            }
        }
        
        /// <remarks/>
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        public string PHONE {
            get {
                return this.pHONEField;
            }
            set {
                this.pHONEField = value;
            }
        }
        
        /// <remarks/>
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
            }
        }
        
        /// <remarks/>
        public string SUFFIX {
            get {
                return this.sUFFIXField;
            }
            set {
                this.sUFFIXField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public string EPREF {
            get {
                return this.ePREFField;
            }
            set {
                this.ePREFField = value;
            }
        }
        
        /// <remarks/>
        public string OPTIN {
            get {
                return this.oPTINField;
            }
            set {
                this.oPTINField = value;
            }
        }
        
        /// <remarks/>
        public string ALTCITY {
            get {
                return this.aLTCITYField;
            }
            set {
                this.aLTCITYField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS_DESC {
            get {
                return this.sTATUS_DESCField;
            }
            set {
                this.sTATUS_DESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class responsetype {
        
        private string uSER_FOUNDField;
        
        private string cUST_FOUNDField;
        
        private string cUSTOMER_NUMBERField;
        
        private string uSERIDField;
        
        private string aUTHField;
        
        private string aCCESSField;
        
        private string sTATUSField;
        
        private customerinfotype cUSTOMER_INFOField;
        
        private shiptotype sHIP_TOField;
        
        private orderhistorytype[] oRDER_HISTORYField;
        
        private suboffertype[] sUB_OFFERSField;
        
        private string tIME_ELAPSEDField;
        
        private string rOUNDTRIP_TIMEField;
        
        private string mEMORY_USEDField;
        
        private string pROTOCOLField;
        
        private string vERSIONField;
        
        private string sERVERField;
        
        private string[] iNFOField;
        
        /// <remarks/>
        public string USER_FOUND {
            get {
                return this.uSER_FOUNDField;
            }
            set {
                this.uSER_FOUNDField = value;
            }
        }
        
        /// <remarks/>
        public string CUST_FOUND {
            get {
                return this.cUST_FOUNDField;
            }
            set {
                this.cUST_FOUNDField = value;
            }
        }
        
        /// <remarks/>
        public string CUSTOMER_NUMBER {
            get {
                return this.cUSTOMER_NUMBERField;
            }
            set {
                this.cUSTOMER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        public string AUTH {
            get {
                return this.aUTHField;
            }
            set {
                this.aUTHField = value;
            }
        }
        
        /// <remarks/>
        public string ACCESS {
            get {
                return this.aCCESSField;
            }
            set {
                this.aCCESSField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public customerinfotype CUSTOMER_INFO {
            get {
                return this.cUSTOMER_INFOField;
            }
            set {
                this.cUSTOMER_INFOField = value;
            }
        }
        
        /// <remarks/>
        public shiptotype SHIP_TO {
            get {
                return this.sHIP_TOField;
            }
            set {
                this.sHIP_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public orderhistorytype[] ORDER_HISTORY {
            get {
                return this.oRDER_HISTORYField;
            }
            set {
                this.oRDER_HISTORYField = value;
            }
        }
        
        /// <remarks/>
        public suboffertype[] SUB_OFFERS {
            get {
                return this.sUB_OFFERSField;
            }
            set {
                this.sUB_OFFERSField = value;
            }
        }
        
        /// <remarks/>
        public string TIME_ELAPSED {
            get {
                return this.tIME_ELAPSEDField;
            }
            set {
                this.tIME_ELAPSEDField = value;
            }
        }
        
        /// <remarks/>
        public string ROUNDTRIP_TIME {
            get {
                return this.rOUNDTRIP_TIMEField;
            }
            set {
                this.rOUNDTRIP_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY_USED {
            get {
                return this.mEMORY_USEDField;
            }
            set {
                this.mEMORY_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string PROTOCOL {
            get {
                return this.pROTOCOLField;
            }
            set {
                this.pROTOCOLField = value;
            }
        }
        
        /// <remarks/>
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
            }
        }
        
        /// <remarks/>
        public string SERVER {
            get {
                return this.sERVERField;
            }
            set {
                this.sERVERField = value;
            }
        }
        
        /// <remarks/>
        public string[] INFO {
            get {
                return this.iNFOField;
            }
            set {
                this.iNFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class errortype {
        
        private string[] errmsgField;
        
        private string errnoField;
        
        /// <remarks/>
        public string[] errmsg {
            get {
                return this.errmsgField;
            }
            set {
                this.errmsgField = value;
            }
        }
        
        /// <remarks/>
        public string errno {
            get {
                return this.errnoField;
            }
            set {
                this.errnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GateKeeper")]
    public partial class returntype {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private errortype[] errorField;
        
        private responsetype responseField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public errortype[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public responsetype response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void process_wsdlCompletedEventHandler(object sender, process_wsdlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class process_wsdlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal process_wsdlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returntype Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returntype)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591