//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5456.
// 
#pragma warning disable 1591

namespace Tests.MobileService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MobileServicesSoap", Namespace="http://andrewharper.com/")]
    public partial class MobileServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHotelOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchSpecialOffersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitContactFormOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MobileServices() {
            this.Url = global::Tests.Properties.Settings.Default.Tests_MobileService_MobileServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotelCompletedEventHandler GetHotelCompleted;
        
        /// <remarks/>
        public event SearchHotelsCompletedEventHandler SearchHotelsCompleted;
        
        /// <remarks/>
        public event SearchSpecialOffersCompletedEventHandler SearchSpecialOffersCompleted;
        
        /// <remarks/>
        public event SubmitContactFormCompletedEventHandler SubmitContactFormCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://andrewharper.com/GetHotel", RequestNamespace="http://andrewharper.com/", ResponseNamespace="http://andrewharper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel GetHotel(int HotelId) {
            object[] results = this.Invoke("GetHotel", new object[] {
                        HotelId});
            return ((Hotel)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelAsync(int HotelId) {
            this.GetHotelAsync(HotelId, null);
        }
        
        /// <remarks/>
        public void GetHotelAsync(int HotelId, object userState) {
            if ((this.GetHotelOperationCompleted == null)) {
                this.GetHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelOperationCompleted);
            }
            this.InvokeAsync("GetHotel", new object[] {
                        HotelId}, this.GetHotelOperationCompleted, userState);
        }
        
        private void OnGetHotelOperationCompleted(object arg) {
            if ((this.GetHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelCompleted(this, new GetHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://andrewharper.com/SearchHotels", RequestNamespace="http://andrewharper.com/", ResponseNamespace="http://andrewharper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel[] SearchHotels(string Name, string City, string Province_Region, string Country) {
            object[] results = this.Invoke("SearchHotels", new object[] {
                        Name,
                        City,
                        Province_Region,
                        Country});
            return ((Hotel[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchHotelsAsync(string Name, string City, string Province_Region, string Country) {
            this.SearchHotelsAsync(Name, City, Province_Region, Country, null);
        }
        
        /// <remarks/>
        public void SearchHotelsAsync(string Name, string City, string Province_Region, string Country, object userState) {
            if ((this.SearchHotelsOperationCompleted == null)) {
                this.SearchHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchHotelsOperationCompleted);
            }
            this.InvokeAsync("SearchHotels", new object[] {
                        Name,
                        City,
                        Province_Region,
                        Country}, this.SearchHotelsOperationCompleted, userState);
        }
        
        private void OnSearchHotelsOperationCompleted(object arg) {
            if ((this.SearchHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchHotelsCompleted(this, new SearchHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://andrewharper.com/SearchSpecialOffers", RequestNamespace="http://andrewharper.com/", ResponseNamespace="http://andrewharper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SpecialOffer[] SearchSpecialOffers(string Name, string City, string Province_Region, string Country) {
            object[] results = this.Invoke("SearchSpecialOffers", new object[] {
                        Name,
                        City,
                        Province_Region,
                        Country});
            return ((SpecialOffer[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchSpecialOffersAsync(string Name, string City, string Province_Region, string Country) {
            this.SearchSpecialOffersAsync(Name, City, Province_Region, Country, null);
        }
        
        /// <remarks/>
        public void SearchSpecialOffersAsync(string Name, string City, string Province_Region, string Country, object userState) {
            if ((this.SearchSpecialOffersOperationCompleted == null)) {
                this.SearchSpecialOffersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchSpecialOffersOperationCompleted);
            }
            this.InvokeAsync("SearchSpecialOffers", new object[] {
                        Name,
                        City,
                        Province_Region,
                        Country}, this.SearchSpecialOffersOperationCompleted, userState);
        }
        
        private void OnSearchSpecialOffersOperationCompleted(object arg) {
            if ((this.SearchSpecialOffersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchSpecialOffersCompleted(this, new SearchSpecialOffersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://andrewharper.com/SubmitContactForm", RequestNamespace="http://andrewharper.com/", ResponseNamespace="http://andrewharper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MobileServicesResponse SubmitContactForm(string FirstName, string LastName, string HotelName, string HotelLocation, int RoomCount, System.DateTime CheckInDate, System.DateTime CheckOutDate, string Phone, string Email, bool IsMember, string Comments) {
            object[] results = this.Invoke("SubmitContactForm", new object[] {
                        FirstName,
                        LastName,
                        HotelName,
                        HotelLocation,
                        RoomCount,
                        CheckInDate,
                        CheckOutDate,
                        Phone,
                        Email,
                        IsMember,
                        Comments});
            return ((MobileServicesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitContactFormAsync(string FirstName, string LastName, string HotelName, string HotelLocation, int RoomCount, System.DateTime CheckInDate, System.DateTime CheckOutDate, string Phone, string Email, bool IsMember, string Comments) {
            this.SubmitContactFormAsync(FirstName, LastName, HotelName, HotelLocation, RoomCount, CheckInDate, CheckOutDate, Phone, Email, IsMember, Comments, null);
        }
        
        /// <remarks/>
        public void SubmitContactFormAsync(string FirstName, string LastName, string HotelName, string HotelLocation, int RoomCount, System.DateTime CheckInDate, System.DateTime CheckOutDate, string Phone, string Email, bool IsMember, string Comments, object userState) {
            if ((this.SubmitContactFormOperationCompleted == null)) {
                this.SubmitContactFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitContactFormOperationCompleted);
            }
            this.InvokeAsync("SubmitContactForm", new object[] {
                        FirstName,
                        LastName,
                        HotelName,
                        HotelLocation,
                        RoomCount,
                        CheckInDate,
                        CheckOutDate,
                        Phone,
                        Email,
                        IsMember,
                        Comments}, this.SubmitContactFormOperationCompleted, userState);
        }
        
        private void OnSubmitContactFormOperationCompleted(object arg) {
            if ((this.SubmitContactFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitContactFormCompleted(this, new SubmitContactFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://andrewharper.com/")]
    public partial class Hotel {
        
        private int hotelIdField;
        
        private string nameField;
        
        private string memberPrivilegesField;
        
        private string overviewField;
        
        private string ratesField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string province_StateField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string[] imagesField;
        
        private string[] thumbnailsField;
        
        private bool isAllianceField;
        
        private float ratingField;
        
        private int[] specialOfferIdsField;
        
        /// <remarks/>
        public int HotelId {
            get {
                return this.hotelIdField;
            }
            set {
                this.hotelIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string MemberPrivileges {
            get {
                return this.memberPrivilegesField;
            }
            set {
                this.memberPrivilegesField = value;
            }
        }
        
        /// <remarks/>
        public string Overview {
            get {
                return this.overviewField;
            }
            set {
                this.overviewField = value;
            }
        }
        
        /// <remarks/>
        public string Rates {
            get {
                return this.ratesField;
            }
            set {
                this.ratesField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Province_State {
            get {
                return this.province_StateField;
            }
            set {
                this.province_StateField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        public string[] Thumbnails {
            get {
                return this.thumbnailsField;
            }
            set {
                this.thumbnailsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAlliance {
            get {
                return this.isAllianceField;
            }
            set {
                this.isAllianceField = value;
            }
        }
        
        /// <remarks/>
        public float Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        public int[] SpecialOfferIds {
            get {
                return this.specialOfferIdsField;
            }
            set {
                this.specialOfferIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://andrewharper.com/")]
    public partial class MobileServicesResponse {
        
        private bool isSuccessField;
        
        private string messageField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://andrewharper.com/")]
    public partial class SpecialOffer {
        
        private int offerIdField;
        
        private string nameField;
        
        private string descriptionField;
        
        private int hotelIdField;
        
        private string[] imagesField;
        
        private string[] thumbnailsField;
        
        /// <remarks/>
        public int OfferId {
            get {
                return this.offerIdField;
            }
            set {
                this.offerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int HotelId {
            get {
                return this.hotelIdField;
            }
            set {
                this.hotelIdField = value;
            }
        }
        
        /// <remarks/>
        public string[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        public string[] Thumbnails {
            get {
                return this.thumbnailsField;
            }
            set {
                this.thumbnailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetHotelCompletedEventHandler(object sender, GetHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SearchHotelsCompletedEventHandler(object sender, SearchHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SearchSpecialOffersCompletedEventHandler(object sender, SearchSpecialOffersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchSpecialOffersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchSpecialOffersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpecialOffer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpecialOffer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SubmitContactFormCompletedEventHandler(object sender, SubmitContactFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitContactFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitContactFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MobileServicesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MobileServicesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591