//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4959.
// 
#pragma warning disable 1591

namespace Tests.SecureServices {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SecureServicesSoap", Namespace="http://tempuri.org/")]
    public partial class SecureServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChargeCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback ForgotPasswordResetOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSubscriptionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SecureServices() {
            this.Url = global::Tests.Properties.Settings.Default.Tests_SecureServices_SecureServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        public event UpdateUserNameCompletedEventHandler UpdateUserNameCompleted;
        
        /// <remarks/>
        public event UpdatePasswordCompletedEventHandler UpdatePasswordCompleted;
        
        /// <remarks/>
        public event ChargeCardCompletedEventHandler ChargeCardCompleted;
        
        /// <remarks/>
        public event ForgotPasswordResetCompletedEventHandler ForgotPasswordResetCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event CreateSubscriptionCompletedEventHandler CreateSubscriptionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResponse CreateUser(string hashed_memberid, string username, string hashed_password, string postalcode) {
            object[] results = this.Invoke("CreateUser", new object[] {
                        hashed_memberid,
                        username,
                        hashed_password,
                        postalcode});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAsync(string hashed_memberid, string username, string hashed_password, string postalcode) {
            this.CreateUserAsync(hashed_memberid, username, hashed_password, postalcode, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(string hashed_memberid, string username, string hashed_password, string postalcode, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        hashed_memberid,
                        username,
                        hashed_password,
                        postalcode}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResponse UpdateUserName(string newusername, string oldusername, string hashed_password) {
            object[] results = this.Invoke("UpdateUserName", new object[] {
                        newusername,
                        oldusername,
                        hashed_password});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserNameAsync(string newusername, string oldusername, string hashed_password) {
            this.UpdateUserNameAsync(newusername, oldusername, hashed_password, null);
        }
        
        /// <remarks/>
        public void UpdateUserNameAsync(string newusername, string oldusername, string hashed_password, object userState) {
            if ((this.UpdateUserNameOperationCompleted == null)) {
                this.UpdateUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserNameOperationCompleted);
            }
            this.InvokeAsync("UpdateUserName", new object[] {
                        newusername,
                        oldusername,
                        hashed_password}, this.UpdateUserNameOperationCompleted, userState);
        }
        
        private void OnUpdateUserNameOperationCompleted(object arg) {
            if ((this.UpdateUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserNameCompleted(this, new UpdateUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResponse UpdatePassword(string username, string hashed_newpassword) {
            object[] results = this.Invoke("UpdatePassword", new object[] {
                        username,
                        hashed_newpassword});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePasswordAsync(string username, string hashed_newpassword) {
            this.UpdatePasswordAsync(username, hashed_newpassword, null);
        }
        
        /// <remarks/>
        public void UpdatePasswordAsync(string username, string hashed_newpassword, object userState) {
            if ((this.UpdatePasswordOperationCompleted == null)) {
                this.UpdatePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePasswordOperationCompleted);
            }
            this.InvokeAsync("UpdatePassword", new object[] {
                        username,
                        hashed_newpassword}, this.UpdatePasswordOperationCompleted, userState);
        }
        
        private void OnUpdatePasswordOperationCompleted(object arg) {
            if ((this.UpdatePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePasswordCompleted(this, new UpdatePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChargeCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResponse ChargeCard(
                    string salutation, 
                    string firstName, 
                    string middleInitial, 
                    string lastName, 
                    string suffix, 
                    string professionalTitle, 
                    string email, 
                    bool optIn, 
                    string businessName, 
                    string address1, 
                    string address2, 
                    string address3, 
                    string city, 
                    string state, 
                    string postalCode, 
                    string country, 
                    string phone, 
                    string fax, 
                    string altCity, 
                    string hashed_ccNumber, 
                    short hashed_ccExpMonth, 
                    short hashed_ccExpYear, 
                    string transactionType, 
                    float amount, 
                    string hashed_ccName, 
                    string hashed_ccAddress, 
                    string hashed_ccCity, 
                    string hashed_ccState, 
                    string hashed_ccPostalCode) {
            object[] results = this.Invoke("ChargeCard", new object[] {
                        salutation,
                        firstName,
                        middleInitial,
                        lastName,
                        suffix,
                        professionalTitle,
                        email,
                        optIn,
                        businessName,
                        address1,
                        address2,
                        address3,
                        city,
                        state,
                        postalCode,
                        country,
                        phone,
                        fax,
                        altCity,
                        hashed_ccNumber,
                        hashed_ccExpMonth,
                        hashed_ccExpYear,
                        transactionType,
                        amount,
                        hashed_ccName,
                        hashed_ccAddress,
                        hashed_ccCity,
                        hashed_ccState,
                        hashed_ccPostalCode});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ChargeCardAsync(
                    string salutation, 
                    string firstName, 
                    string middleInitial, 
                    string lastName, 
                    string suffix, 
                    string professionalTitle, 
                    string email, 
                    bool optIn, 
                    string businessName, 
                    string address1, 
                    string address2, 
                    string address3, 
                    string city, 
                    string state, 
                    string postalCode, 
                    string country, 
                    string phone, 
                    string fax, 
                    string altCity, 
                    string hashed_ccNumber, 
                    short hashed_ccExpMonth, 
                    short hashed_ccExpYear, 
                    string transactionType, 
                    float amount, 
                    string hashed_ccName, 
                    string hashed_ccAddress, 
                    string hashed_ccCity, 
                    string hashed_ccState, 
                    string hashed_ccPostalCode) {
            this.ChargeCardAsync(salutation, firstName, middleInitial, lastName, suffix, professionalTitle, email, optIn, businessName, address1, address2, address3, city, state, postalCode, country, phone, fax, altCity, hashed_ccNumber, hashed_ccExpMonth, hashed_ccExpYear, transactionType, amount, hashed_ccName, hashed_ccAddress, hashed_ccCity, hashed_ccState, hashed_ccPostalCode, null);
        }
        
        /// <remarks/>
        public void ChargeCardAsync(
                    string salutation, 
                    string firstName, 
                    string middleInitial, 
                    string lastName, 
                    string suffix, 
                    string professionalTitle, 
                    string email, 
                    bool optIn, 
                    string businessName, 
                    string address1, 
                    string address2, 
                    string address3, 
                    string city, 
                    string state, 
                    string postalCode, 
                    string country, 
                    string phone, 
                    string fax, 
                    string altCity, 
                    string hashed_ccNumber, 
                    short hashed_ccExpMonth, 
                    short hashed_ccExpYear, 
                    string transactionType, 
                    float amount, 
                    string hashed_ccName, 
                    string hashed_ccAddress, 
                    string hashed_ccCity, 
                    string hashed_ccState, 
                    string hashed_ccPostalCode, 
                    object userState) {
            if ((this.ChargeCardOperationCompleted == null)) {
                this.ChargeCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChargeCardOperationCompleted);
            }
            this.InvokeAsync("ChargeCard", new object[] {
                        salutation,
                        firstName,
                        middleInitial,
                        lastName,
                        suffix,
                        professionalTitle,
                        email,
                        optIn,
                        businessName,
                        address1,
                        address2,
                        address3,
                        city,
                        state,
                        postalCode,
                        country,
                        phone,
                        fax,
                        altCity,
                        hashed_ccNumber,
                        hashed_ccExpMonth,
                        hashed_ccExpYear,
                        transactionType,
                        amount,
                        hashed_ccName,
                        hashed_ccAddress,
                        hashed_ccCity,
                        hashed_ccState,
                        hashed_ccPostalCode}, this.ChargeCardOperationCompleted, userState);
        }
        
        private void OnChargeCardOperationCompleted(object arg) {
            if ((this.ChargeCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChargeCardCompleted(this, new ChargeCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ForgotPasswordReset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResponse ForgotPasswordReset(string email) {
            object[] results = this.Invoke("ForgotPasswordReset", new object[] {
                        email});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ForgotPasswordResetAsync(string email) {
            this.ForgotPasswordResetAsync(email, null);
        }
        
        /// <remarks/>
        public void ForgotPasswordResetAsync(string email, object userState) {
            if ((this.ForgotPasswordResetOperationCompleted == null)) {
                this.ForgotPasswordResetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnForgotPasswordResetOperationCompleted);
            }
            this.InvokeAsync("ForgotPasswordReset", new object[] {
                        email}, this.ForgotPasswordResetOperationCompleted, userState);
        }
        
        private void OnForgotPasswordResetOperationCompleted(object arg) {
            if ((this.ForgotPasswordResetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ForgotPasswordResetCompleted(this, new ForgotPasswordResetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResponse Login(string username, string hashed_password, string hashed_cusid, string screenname) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        hashed_password,
                        hashed_cusid,
                        screenname});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string hashed_password, string hashed_cusid, string screenname) {
            this.LoginAsync(username, hashed_password, hashed_cusid, screenname, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string hashed_password, string hashed_cusid, string screenname, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        hashed_password,
                        hashed_cusid,
                        screenname}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateSubscription", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResponse CreateSubscription() {
            object[] results = this.Invoke("CreateSubscription", new object[0]);
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSubscriptionAsync() {
            this.CreateSubscriptionAsync(null);
        }
        
        /// <remarks/>
        public void CreateSubscriptionAsync(object userState) {
            if ((this.CreateSubscriptionOperationCompleted == null)) {
                this.CreateSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSubscriptionOperationCompleted);
            }
            this.InvokeAsync("CreateSubscription", new object[0], this.CreateSubscriptionOperationCompleted, userState);
        }
        
        private void OnCreateSubscriptionOperationCompleted(object arg) {
            if ((this.CreateSubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSubscriptionCompleted(this, new CreateSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseResponse {
        
        private SFGResponse typedResponseField;
        
        private Message[] messagesField;
        
        private Message[] debugLogField;
        
        private string[] debugStringLogField;
        
        /// <remarks/>
        public SFGResponse TypedResponse {
            get {
                return this.typedResponseField;
            }
            set {
                this.typedResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Messages")]
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DebugLog")]
        public Message[] DebugLog {
            get {
                return this.debugLogField;
            }
            set {
                this.debugLogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DebugStringLog")]
        public string[] DebugStringLog {
            get {
                return this.debugStringLogField;
            }
            set {
                this.debugStringLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferralResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GatekeeperServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetMemberResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FatalErrorResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCardServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerUpdateServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateMemberResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AHResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserMaintenanceServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateLoginResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdatePasswordResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateUsernameResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriptionServiceResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class SFGResponse {
        
        private bool successField;
        
        private string[] infoField;
        
        private string memoryUsedField;
        
        private OptinResults[] optinResultsField;
        
        private string protocolField;
        
        private string roundtripTimeField;
        
        private string serverField;
        
        private string timeElapsedField;
        
        private string versionField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Info")]
        public string[] Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public string MemoryUsed {
            get {
                return this.memoryUsedField;
            }
            set {
                this.memoryUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OptinResults")]
        public OptinResults[] OptinResults {
            get {
                return this.optinResultsField;
            }
            set {
                this.optinResultsField = value;
            }
        }
        
        /// <remarks/>
        public string Protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        public string RoundtripTime {
            get {
                return this.roundtripTimeField;
            }
            set {
                this.roundtripTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        public string TimeElapsed {
            get {
                return this.timeElapsedField;
            }
            set {
                this.timeElapsedField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OptinResults {
        
        private string emailIdField;
        
        private string emailField;
        
        private string memberIdField;
        
        private string epTextIdField;
        
        private string epTypeField;
        
        private string productLineField;
        
        private string optinField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private bool successSpecified1Field;
        
        private string[] errorsField;
        
        private string sourceField;
        
        /// <remarks/>
        public string EmailId {
            get {
                return this.emailIdField;
            }
            set {
                this.emailIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public string EpTextId {
            get {
                return this.epTextIdField;
            }
            set {
                this.epTextIdField = value;
            }
        }
        
        /// <remarks/>
        public string EpType {
            get {
                return this.epTypeField;
            }
            set {
                this.epTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductLine {
            get {
                return this.productLineField;
            }
            set {
                this.productLineField = value;
            }
        }
        
        /// <remarks/>
        public string Optin {
            get {
                return this.optinField;
            }
            set {
                this.optinField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SuccessSpecified")]
        public bool SuccessSpecified1 {
            get {
                return this.successSpecified1Field;
            }
            set {
                this.successSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message {
        
        private string sfgCodeField;
        
        private string sfgNameField;
        
        private string[] sfgMessagesField;
        
        private short ahCodeField;
        
        private string ahNameField;
        
        private string ahMessageField;
        
        private string methodNameField;
        
        private MessageSources messageSourceField;
        
        /// <remarks/>
        public string SfgCode {
            get {
                return this.sfgCodeField;
            }
            set {
                this.sfgCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SfgName {
            get {
                return this.sfgNameField;
            }
            set {
                this.sfgNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SfgMessages")]
        public string[] SfgMessages {
            get {
                return this.sfgMessagesField;
            }
            set {
                this.sfgMessagesField = value;
            }
        }
        
        /// <remarks/>
        public short AhCode {
            get {
                return this.ahCodeField;
            }
            set {
                this.ahCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AhName {
            get {
                return this.ahNameField;
            }
            set {
                this.ahNameField = value;
            }
        }
        
        /// <remarks/>
        public string AhMessage {
            get {
                return this.ahMessageField;
            }
            set {
                this.ahMessageField = value;
            }
        }
        
        /// <remarks/>
        public string MethodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        public MessageSources MessageSource {
            get {
                return this.messageSourceField;
            }
            set {
                this.messageSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MessageSources {
        
        /// <remarks/>
        AndrewHarper,
        
        /// <remarks/>
        SfgCommon,
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        CreditCard,
        
        /// <remarks/>
        CustomerUpdate,
        
        /// <remarks/>
        Gatekeeper,
        
        /// <remarks/>
        SubOrderInsert,
        
        /// <remarks/>
        UserMaint,
        
        /// <remarks/>
        Heartbeat,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RenewalOffer {
        
        private string keyCodeField;
        
        private string publicationCodeField;
        
        private string agencyCodeField;
        
        private string countryCodeField;
        
        private char subRenewalFlagField;
        
        private string subscriptionTermField;
        
        private char cashOrCreditOfferField;
        
        private decimal grossValueField;
        
        private System.DateTime startDateField;
        
        private string startIssueField;
        
        private short numberFreeIssuesField;
        
        private string startBillingIssueField;
        
        private short numberGraceIssuesField;
        
        private short numberOfInstallmentsField;
        
        private decimal postageField;
        
        /// <remarks/>
        public string KeyCode {
            get {
                return this.keyCodeField;
            }
            set {
                this.keyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PublicationCode {
            get {
                return this.publicationCodeField;
            }
            set {
                this.publicationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public char SubRenewalFlag {
            get {
                return this.subRenewalFlagField;
            }
            set {
                this.subRenewalFlagField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriptionTerm {
            get {
                return this.subscriptionTermField;
            }
            set {
                this.subscriptionTermField = value;
            }
        }
        
        /// <remarks/>
        public char CashOrCreditOffer {
            get {
                return this.cashOrCreditOfferField;
            }
            set {
                this.cashOrCreditOfferField = value;
            }
        }
        
        /// <remarks/>
        public decimal GrossValue {
            get {
                return this.grossValueField;
            }
            set {
                this.grossValueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string StartIssue {
            get {
                return this.startIssueField;
            }
            set {
                this.startIssueField = value;
            }
        }
        
        /// <remarks/>
        public short NumberFreeIssues {
            get {
                return this.numberFreeIssuesField;
            }
            set {
                this.numberFreeIssuesField = value;
            }
        }
        
        /// <remarks/>
        public string StartBillingIssue {
            get {
                return this.startBillingIssueField;
            }
            set {
                this.startBillingIssueField = value;
            }
        }
        
        /// <remarks/>
        public short NumberGraceIssues {
            get {
                return this.numberGraceIssuesField;
            }
            set {
                this.numberGraceIssuesField = value;
            }
        }
        
        /// <remarks/>
        public short NumberOfInstallments {
            get {
                return this.numberOfInstallmentsField;
            }
            set {
                this.numberOfInstallmentsField = value;
            }
        }
        
        /// <remarks/>
        public decimal Postage {
            get {
                return this.postageField;
            }
            set {
                this.postageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Subscription {
        
        private SubscriptionCategory categoryField;
        
        private string publicationCodeField;
        
        private string descriptionField;
        
        private int qtyField;
        
        private string dateEnteredField;
        
        private string expireDateField;
        
        private int issuesRemainingField;
        
        private string renewalKeycodeField;
        
        private bool ePubField;
        
        private string subscribingMemberField;
        
        private string giftRecipientField;
        
        private decimal outstandingBalanceField;
        
        private string statusFlagField;
        
        private bool isGiftField;
        
        private bool isDonorField;
        
        /// <remarks/>
        public SubscriptionCategory Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string PublicationCode {
            get {
                return this.publicationCodeField;
            }
            set {
                this.publicationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string DateEntered {
            get {
                return this.dateEnteredField;
            }
            set {
                this.dateEnteredField = value;
            }
        }
        
        /// <remarks/>
        public string ExpireDate {
            get {
                return this.expireDateField;
            }
            set {
                this.expireDateField = value;
            }
        }
        
        /// <remarks/>
        public int IssuesRemaining {
            get {
                return this.issuesRemainingField;
            }
            set {
                this.issuesRemainingField = value;
            }
        }
        
        /// <remarks/>
        public string RenewalKeycode {
            get {
                return this.renewalKeycodeField;
            }
            set {
                this.renewalKeycodeField = value;
            }
        }
        
        /// <remarks/>
        public bool EPub {
            get {
                return this.ePubField;
            }
            set {
                this.ePubField = value;
            }
        }
        
        /// <remarks/>
        public string SubscribingMember {
            get {
                return this.subscribingMemberField;
            }
            set {
                this.subscribingMemberField = value;
            }
        }
        
        /// <remarks/>
        public string GiftRecipient {
            get {
                return this.giftRecipientField;
            }
            set {
                this.giftRecipientField = value;
            }
        }
        
        /// <remarks/>
        public decimal OutstandingBalance {
            get {
                return this.outstandingBalanceField;
            }
            set {
                this.outstandingBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string StatusFlag {
            get {
                return this.statusFlagField;
            }
            set {
                this.statusFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool IsGift {
            get {
                return this.isGiftField;
            }
            set {
                this.isGiftField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDonor {
            get {
                return this.isDonorField;
            }
            set {
                this.isDonorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SubscriptionCategory {
        
        /// <remarks/>
        Publication,
        
        /// <remarks/>
        Catalog,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Address {
        
        private string stateField;
        
        private string stateCodeField;
        
        private string businessNameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string phoneField;
        
        private string faxField;
        
        private string altCityField;
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessName {
            get {
                return this.businessNameField;
            }
            set {
                this.businessNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string AltCity {
            get {
                return this.altCityField;
            }
            set {
                this.altCityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Member {
        
        private Address addressField;
        
        private string statusFlagField;
        
        private Subscription[] subscriptionsField;
        
        private bool optInField;
        
        private string cusIdField;
        
        private string cusCustNumField;
        
        private string screenNameField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string emailField;
        
        private string memberIdField;
        
        private string salutationField;
        
        private string firstNameField;
        
        private string middleInitialField;
        
        private string lastNameField;
        
        private string suffixField;
        
        private string professionalTitleField;
        
        /// <remarks/>
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string StatusFlag {
            get {
                return this.statusFlagField;
            }
            set {
                this.statusFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subscriptions")]
        public Subscription[] Subscriptions {
            get {
                return this.subscriptionsField;
            }
            set {
                this.subscriptionsField = value;
            }
        }
        
        /// <remarks/>
        public bool OptIn {
            get {
                return this.optInField;
            }
            set {
                this.optInField = value;
            }
        }
        
        /// <remarks/>
        public string CusId {
            get {
                return this.cusIdField;
            }
            set {
                this.cusIdField = value;
            }
        }
        
        /// <remarks/>
        public string CusCustNum {
            get {
                return this.cusCustNumField;
            }
            set {
                this.cusCustNumField = value;
            }
        }
        
        /// <remarks/>
        public string ScreenName {
            get {
                return this.screenNameField;
            }
            set {
                this.screenNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleInitial {
            get {
                return this.middleInitialField;
            }
            set {
                this.middleInitialField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string ProfessionalTitle {
            get {
                return this.professionalTitleField;
            }
            set {
                this.professionalTitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriptionValidation {
        
        private bool accessField;
        
        private string statusFlagField;
        
        /// <remarks/>
        public bool Access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        public string StatusFlag {
            get {
                return this.statusFlagField;
            }
            set {
                this.statusFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailResultType {
        
        private string emailIdField;
        
        private string emailField;
        
        private string memberIdField;
        
        private string emailTypeField;
        
        private string emailActiveField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private bool successSpecified1Field;
        
        private string[] errorsField;
        
        private string sourceField;
        
        private string updateAllField;
        
        private string processTypeField;
        
        private string emailStatusField;
        
        /// <remarks/>
        public string EmailId {
            get {
                return this.emailIdField;
            }
            set {
                this.emailIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public string EmailType {
            get {
                return this.emailTypeField;
            }
            set {
                this.emailTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EmailActive {
            get {
                return this.emailActiveField;
            }
            set {
                this.emailActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SuccessSpecified")]
        public bool SuccessSpecified1 {
            get {
                return this.successSpecified1Field;
            }
            set {
                this.successSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateAll {
            get {
                return this.updateAllField;
            }
            set {
                this.updateAllField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessType {
            get {
                return this.processTypeField;
            }
            set {
                this.processTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EmailStatus {
            get {
                return this.emailStatusField;
            }
            set {
                this.emailStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReferralResponse : SFGResponse {
        
        private int referralidField;
        
        /// <remarks/>
        public int referralid {
            get {
                return this.referralidField;
            }
            set {
                this.referralidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetMemberResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class GatekeeperServiceResponse : SFGResponse {
        
        private bool webAccountFoundField;
        
        private bool memberFoundField;
        
        private bool authenticatedField;
        
        private SubscriptionValidation subscriptionValidationDataField;
        
        private Member memberDataField;
        
        private RenewalOffer[] renewalOffersField;
        
        private Address shipToAddressField;
        
        /// <remarks/>
        public bool WebAccountFound {
            get {
                return this.webAccountFoundField;
            }
            set {
                this.webAccountFoundField = value;
            }
        }
        
        /// <remarks/>
        public bool MemberFound {
            get {
                return this.memberFoundField;
            }
            set {
                this.memberFoundField = value;
            }
        }
        
        /// <remarks/>
        public bool Authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        public SubscriptionValidation SubscriptionValidationData {
            get {
                return this.subscriptionValidationDataField;
            }
            set {
                this.subscriptionValidationDataField = value;
            }
        }
        
        /// <remarks/>
        public Member MemberData {
            get {
                return this.memberDataField;
            }
            set {
                this.memberDataField = value;
            }
        }
        
        /// <remarks/>
        public RenewalOffer[] RenewalOffers {
            get {
                return this.renewalOffersField;
            }
            set {
                this.renewalOffersField = value;
            }
        }
        
        /// <remarks/>
        public Address ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponse : GatekeeperServiceResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberResponse : GatekeeperServiceResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FatalErrorResponse : SFGResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PingResponse : SFGResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCardServiceResponse : SFGResponse {
        
        private bool transactionSucceededField;
        
        private string verifoneRoutingIdField;
        
        private string authorizationCodeField;
        
        private string responseCodeField;
        
        private string memberIdField;
        
        private bool memberUpdatedField;
        
        private EmailResultType[] emailResultsField;
        
        /// <remarks/>
        public bool TransactionSucceeded {
            get {
                return this.transactionSucceededField;
            }
            set {
                this.transactionSucceededField = value;
            }
        }
        
        /// <remarks/>
        public string VerifoneRoutingId {
            get {
                return this.verifoneRoutingIdField;
            }
            set {
                this.verifoneRoutingIdField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public bool MemberUpdated {
            get {
                return this.memberUpdatedField;
            }
            set {
                this.memberUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailResults")]
        public EmailResultType[] EmailResults {
            get {
                return this.emailResultsField;
            }
            set {
                this.emailResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateMemberResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerUpdateServiceResponse : SFGResponse {
        
        private bool memberUpdatedField;
        
        /// <remarks/>
        public bool MemberUpdated {
            get {
                return this.memberUpdatedField;
            }
            set {
                this.memberUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMemberResponse : CustomerUpdateServiceResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AHResponse : SFGResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateLoginResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdatePasswordResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateUsernameResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class UserMaintenanceServiceResponse : SFGResponse {
        
        private bool updateSucceededField;
        
        /// <remarks/>
        public bool UpdateSucceeded {
            get {
                return this.updateSucceededField;
            }
            set {
                this.updateSucceededField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateLoginResponse : UserMaintenanceServiceResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePasswordResponse : UserMaintenanceServiceResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUsernameResponse : UserMaintenanceServiceResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriptionServiceResponse : SFGResponse {
        
        private EmailResultType[] memberEmailResultsField;
        
        private OptinResults[] memberOptinResultsField;
        
        private EmailResultType[] gifteeEmailResultsField;
        
        private OptinResults[] gifteeOptinResultsField;
        
        private bool orderAddedField;
        
        private string memberIdField;
        
        private string memberUpdatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberEmailResults")]
        public EmailResultType[] MemberEmailResults {
            get {
                return this.memberEmailResultsField;
            }
            set {
                this.memberEmailResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberOptinResults")]
        public OptinResults[] MemberOptinResults {
            get {
                return this.memberOptinResultsField;
            }
            set {
                this.memberOptinResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GifteeEmailResults")]
        public EmailResultType[] GifteeEmailResults {
            get {
                return this.gifteeEmailResultsField;
            }
            set {
                this.gifteeEmailResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GifteeOptinResults")]
        public OptinResults[] GifteeOptinResults {
            get {
                return this.gifteeOptinResultsField;
            }
            set {
                this.gifteeOptinResultsField = value;
            }
        }
        
        /// <remarks/>
        public bool OrderAdded {
            get {
                return this.orderAddedField;
            }
            set {
                this.orderAddedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MemberUpdated {
            get {
                return this.memberUpdatedField;
            }
            set {
                this.memberUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateUserNameCompletedEventHandler(object sender, UpdateUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdatePasswordCompletedEventHandler(object sender, UpdatePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ChargeCardCompletedEventHandler(object sender, ChargeCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChargeCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChargeCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ForgotPasswordResetCompletedEventHandler(object sender, ForgotPasswordResetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForgotPasswordResetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ForgotPasswordResetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateSubscriptionCompletedEventHandler(object sender, CreateSubscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591