//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace SFGWrapper.SFG.HeartbeatSvc {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="process_wsdl_classBinding", Namespace="urn:Heartbeat")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(errortype))]
    public partial class HeartbeatService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback process_wsdlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HeartbeatService() {
            this.Url = global::SFGWrapper.Properties.Settings.Default.SFGWrapper_com_strategicfulfillment_webservices_HeartbeatService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event process_wsdlCompletedEventHandler process_wsdlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:process_wsdl_classAction", RequestNamespace="urn:Heartbeat", ResponseNamespace="urn:Heartbeat")]
        [return: System.Xml.Serialization.SoapElementAttribute("process_wsdlReturn")]
        public returntype process_wsdl(argtype args) {
            object[] results = this.Invoke("process_wsdl", new object[] {
                        args});
            return ((returntype)(results[0]));
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args) {
            this.process_wsdlAsync(args, null);
        }
        
        /// <remarks/>
        public void process_wsdlAsync(argtype args, object userState) {
            if ((this.process_wsdlOperationCompleted == null)) {
                this.process_wsdlOperationCompleted = new System.Threading.SendOrPostCallback(this.Onprocess_wsdlOperationCompleted);
            }
            this.InvokeAsync("process_wsdl", new object[] {
                        args}, this.process_wsdlOperationCompleted, userState);
        }
        
        private void Onprocess_wsdlOperationCompleted(object arg) {
            if ((this.process_wsdlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.process_wsdlCompleted(this, new process_wsdlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Heartbeat")]
    public partial class argtype {
        
        private string orgField;
        
        private string test_modeField;
        
        private string as_partnerField;
        
        private string db_nameField;
        
        private string app_versionField;
        
        private string is_network_monitorField;
        
        /// <remarks/>
        public string org {
            get {
                return this.orgField;
            }
            set {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        public string test_mode {
            get {
                return this.test_modeField;
            }
            set {
                this.test_modeField = value;
            }
        }
        
        /// <remarks/>
        public string as_partner {
            get {
                return this.as_partnerField;
            }
            set {
                this.as_partnerField = value;
            }
        }
        
        /// <remarks/>
        public string db_name {
            get {
                return this.db_nameField;
            }
            set {
                this.db_nameField = value;
            }
        }
        
        /// <remarks/>
        public string app_version {
            get {
                return this.app_versionField;
            }
            set {
                this.app_versionField = value;
            }
        }
        
        /// <remarks/>
        public string is_network_monitor {
            get {
                return this.is_network_monitorField;
            }
            set {
                this.is_network_monitorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Heartbeat")]
    public partial class responsetype {
        
        private string sTATUSField;
        
        private string tIME_ELAPSEDField;
        
        private string rOUNDTRIP_TIMEField;
        
        private string mEMORY_USEDField;
        
        private string pROTOCOLField;
        
        private string vERSIONField;
        
        private string sERVERField;
        
        private string[] iNFOField;
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string TIME_ELAPSED {
            get {
                return this.tIME_ELAPSEDField;
            }
            set {
                this.tIME_ELAPSEDField = value;
            }
        }
        
        /// <remarks/>
        public string ROUNDTRIP_TIME {
            get {
                return this.rOUNDTRIP_TIMEField;
            }
            set {
                this.rOUNDTRIP_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY_USED {
            get {
                return this.mEMORY_USEDField;
            }
            set {
                this.mEMORY_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string PROTOCOL {
            get {
                return this.pROTOCOLField;
            }
            set {
                this.pROTOCOLField = value;
            }
        }
        
        /// <remarks/>
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
            }
        }
        
        /// <remarks/>
        public string SERVER {
            get {
                return this.sERVERField;
            }
            set {
                this.sERVERField = value;
            }
        }
        
        /// <remarks/>
        public string[] INFO {
            get {
                return this.iNFOField;
            }
            set {
                this.iNFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Heartbeat")]
    public partial class errortype {
        
        private string[] errmsgField;
        
        private string errnoField;
        
        /// <remarks/>
        public string[] errmsg {
            get {
                return this.errmsgField;
            }
            set {
                this.errmsgField = value;
            }
        }
        
        /// <remarks/>
        public string errno {
            get {
                return this.errnoField;
            }
            set {
                this.errnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Heartbeat")]
    public partial class returntype {
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private errortype[] errorField;
        
        private responsetype responseField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public errortype[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public responsetype response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void process_wsdlCompletedEventHandler(object sender, process_wsdlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class process_wsdlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal process_wsdlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returntype Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returntype)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591